"""Initial migration.

Revision ID: 3afdf6cc6b51
Revises: 
Create Date: 2024-08-02 16:49:43.710766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3afdf6cc6b51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_number', sa.Integer(), nullable=False),
    sa.Column('pet_name', sa.String(length=100), nullable=False),
    sa.Column('pet_breed', sa.String(length=100), nullable=False),
    sa.Column('walk_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
